# -*- coding: utf-8 -*-
"""Limpieza.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bwXR13v8Pt1OA41tvL3sSrD2fFgrOSu4
"""

!pip install pypdf python-docx openpyxl pandas -q

# Importación
import gc
import logging
import os
import re
from datetime import datetime
from pathlib import Path
import warnings

import docx
import pandas as pd
import pypdf
from google.colab import drive

# Silenciar advertencias de lectura PDF
for logger_name in ["pypdf", "pypdf._cmap", "pypdf._reader"]:
    logger = logging.getLogger(logger_name)
    logger.setLevel(logging.CRITICAL)
    logger.propagate = False
warnings.filterwarnings("ignore")

# Montar Google Drive
drive.mount("/content/drive", force_remount=True)

# ------------------------------------------------------------------------------
# 1. FUNCIONES DE LECTURA MULTIFORMATO
# ------------------------------------------------------------------------------


def leer_txt(ruta_archivo):
    try:
        with open(ruta_archivo, "r", encoding="utf-8", errors="ignore") as f:
            return f.read()
    except Exception as e:
        return f"[Error leyendo TXT: {str(e)}]"


def leer_pdf(ruta_archivo):
    texto_paginas = []
    try:
        lector = pypdf.PdfReader(ruta_archivo)
        for pagina in lector.pages:
            try:
                contenido = pagina.extract_text()
                if contenido:
                    texto_paginas.append(contenido)
            except Exception:
                continue
    except Exception as e:
        return f"[Error leyendo PDF: {str(e)}]"
    return "\n".join(texto_paginas)


def leer_word(ruta_archivo):
    try:
        doc = docx.Document(ruta_archivo)
        contenido = []
        for p in doc.paragraphs:
            if p.text.strip():
                contenido.append(p.text.strip())

        for table in doc.tables:
            contenido.append("\n--- TABLA EXTRAÍDA ---")
            for row in table.rows:
                fila_texto = [
                    cell.text.strip() for cell in row.cells if cell.text.strip()
                ]
                if fila_texto:
                    contenido.append(" | ".join(fila_texto))
            contenido.append("----------------------\n")

        return "\n".join(contenido)
    except Exception as e:
        return f"[Error leyendo DOCX: {str(e)}]"


def leer_excel(ruta_archivo):
    try:
        dict_hojas = pd.read_excel(ruta_archivo, sheet_name=None)
        texto_completo = []
        for nombre_hoja, df in dict_hojas.items():
            texto_completo.append(f"--- Hoja: {nombre_hoja} ---")
            texto_completo.append(df.to_string(index=False))
        return "\n".join(texto_completo)
    except Exception as e:
        return f"[Error leyendo Excel: {str(e)}]"

# ------------------------------------------------------------------------------
# 2. LIMPIEZA PROFUNDA DE BOILERPLATE Y CARACTERES ESPECIALES (REGEX)
# ------------------------------------------------------------------------------


def normalizar_caracteres_y_tildes(texto: str) -> str:
    """Corrige signos atípicos, comillas extrañas y normaliza espacio/tildes."""
    # Normalizar comillas, guiones y caracteres atípicos
    reemplazos_caracteres = {
        r"[“”«»]": '"',
        r"[‘’`´]": "'",
        r"–": "-",
        r"—": "-",
        r"\t": " ",
        r"\f": "",
        r"\v": "",
    }
    for patron, reemplazo in reemplazos_caracteres.items():
        texto = re.sub(patron, reemplazo, texto)

    return texto


def remover_boilerplate_regex(texto: str) -> str:
    """Filtra encabezados, pies de página, sellos leychile.cl, códigos N10948 y firmas."""
    if not texto or texto.startswith("[Error"):
        return ""

    # Remoción de marcas de agua y metadatos de leychile.cl / BCN
    texto = re.sub(
        r"Biblioteca del Congreso Nacional de Chile\s*-\s*www\.leychile\.cl\s*-\s*documento generado el.*?\n",
        "",
        texto,
        flags=re.IGNORECASE,
    )
    texto = re.sub(
        r"www\.leychile\.cl\s*;\s*codigo\s*:\s*[A-Z0-9]+",
        "",
        texto,
        flags=re.IGNORECASE,
    )
    texto = re.sub(
        r"leychile\.cl\s*/\s*N\d+", "", texto, flags=re.IGNORECASE
    )
    texto = re.sub(
        r"https?://www\.leychile\.cl/N\?\w+", "", texto, flags=re.IGNORECASE
    )
    texto = re.sub(r"\bN10948\b|\bN\d{5,}\b", "", texto)

    # B. Remoción de firmas electrónicas y sellos de validación
    texto = re.sub(
        r"Documento firmado electrónicamente de acuerdo a la Ley N°\s*\d+\.\d+.*?\n",
        "",
        texto,
        flags=re.IGNORECASE,
    )
    texto = re.sub(
        r"CVE\s*:\s*\d+|Código de Verificación:.*?\n",
        "",
        texto,
        flags=re.IGNORECASE,
    )

    # Remoción de encabezados/pies recurrentes (NCh, ISO, Copyright)
    texto = re.sub(
        r"capítulo \d+ de esta norma.*?\n", "", texto, flags=re.IGNORECASE
    )
    texto = re.sub(
        r"NORMA CHILENA OFICIAL.*?\n", "", texto, flags=re.IGNORECASE
    )
    texto = re.sub(
        r"ISO 14001:\d+ \(traducción oficial\)", "", texto, flags=re.IGNORECASE
    )
    texto = re.sub(
        r"DOCUMENTO PROTEGIDO POR COPYRIGHT.*?\n", "", texto, flags=re.IGNORECASE
    )
    texto = re.sub(r"página \d+ de \d+", "", texto, flags=re.IGNORECASE)

    # Limpieza de guiones de relleno e índices
    texto = re.sub(r"\.{3,}\s*\d+", "", texto)
    texto = re.sub(r"_{2,}", " ", texto)

    # Normalización de saltos y espacios
    texto = normalizar_caracteres_y_tildes(texto)
    texto = re.sub(r"[ \t]+", " ", texto)
    texto = re.sub(r"\n{3,}", "\n\n", texto)

    return texto.strip()


def unificar_terminos(texto: str) -> str:
    """Estandariza siglas y abreviaturas normativas."""
    reemplazos = {
        r"\bOAL\b": "Organismo Administrador de la Ley",
        r"\bSEREMI\b": "Secretaría Regional Ministerial",
        r"\bMINSAL\b": "Ministerio de Salud",
        r"\bISP\b": "Instituto de Salud Pública de Chile",
        r"\bS\.S\.O\.\b|\bSSO\b": "Seguridad y Salud Ocupacional",
        r"\bS\.S\.T\.\b|\bSST\b": "Seguridad y Salud en el Trabajo",
        r"\bArt\.\b|\bArt\b": "Artículo",
        r"\bDto\b\.?|\bDTO\b\.?": "Decreto",
        r"\bR\.M\.\b": "Resolución Ministerial",
        r"\bD\.S\.\b": "Decreto Supremo",
        r"\bRes\.\b|\bRES\.\b": "Resolución",
    }
    for patron, reemplazo in reemplazos.items():
        texto = re.sub(patron, reemplazo, texto, flags=re.IGNORECASE)
    return texto

# ------------------------------------------------------------------------------
# 3. ESTRUCTURACIÓN JERÁRQUICA EN MARKDOWN (SIN ALTERAR EL TEXTO ORIGINAL)
# ------------------------------------------------------------------------------


def estructurar_jerarquia_markdown(texto: str) -> str:
    """Aplica formato Markdown jerárquico (#, ##, ###) respetando el contenido intacto."""
    lineas = texto.split("\n")
    lineas_procesadas = []

    for linea in lineas:
        linea_str = linea.strip()
        if not linea_str:
            continue

        # Títulos de nivel 1 (TÍTULOS, LIBROS, CAPÍTULOS, ANEXOS)
        if re.match(
            r"^(ANEXO|TÍTULO|TITULO|LIBRO|CAPÍTULO|CAPITULO)\s+[A-Z0-9\.\-]+",
            linea_str,
            re.IGNORECASE,
        ):
            lineas_procesadas.append(f"\n## {linea_str}\n")
        # Títulos de nivel 2 (Numerales principales ej. 1. OBJETIVO, 2.1 ALCANCE)
        elif re.match(r"^\d{1,2}\.(\d{1,2})?\s+[A-ZÁÉÍÓÚÑ]{3,}", linea_str):
            lineas_procesadas.append(f"\n### {linea_str}\n")
        # Artículos (ej. Artículo 1.-)
        elif re.match(
            r"^(Artículo|Articulo)\s+\d+[\.\°\º\–\-]*",
            linea_str,
            re.IGNORECASE,
        ):
            lineas_procesadas.append(f"\n#### {linea_str}\n")
        else:
            lineas_procesadas.append(linea_str)

    return "\n".join(lineas_procesadas)

# ------------------------------------------------------------------------------
# 4. PIPELINE PRINCIPAL DE EXPORTACIÓN
# ------------------------------------------------------------------------------


def procesar_carpeta_sso(
    ruta_carpeta_origen, ruta_carpeta_destino="./salida_markdown_limpio"
):
    print(
        f"[{datetime.now().strftime('%H:%M:%S')}] ⌨︎ Iniciando procesamiento y limpieza estricta..."
    )

    origen = Path(ruta_carpeta_origen)
    destino = Path(ruta_carpeta_destino)
    destino.mkdir(parents=True, exist_ok=True)

    extensiones = {".pdf", ".docx", ".txt", ".xlsx", ".xls"}
    archivos = [
        f
        for f in origen.rglob("*")
        if f.is_file() and f.suffix.lower() in extensiones
    ]

    procesados = 0
    for i, archivo in enumerate(archivos, 1):
        ext = archivo.suffix.lower()

        if ext == ".pdf":
            raw = leer_pdf(archivo)
        elif ext == ".docx":
            raw = leer_word(archivo)
        elif ext == ".txt":
            raw = leer_txt(archivo)
        elif ext in [".xlsx", ".xls"]:
            raw = leer_excel(archivo)
        else:
            continue

        # Limpieza de ruido Regex
        contenido_limpio = remover_boilerplate_regex(raw)

        if not contenido_limpio:
            contenido_final = (
                "*[Nota: Documento escaneado o sin texto digital extraíble]*"
            )
        else:
            # Unificación de términos
            contenido_unificado = unificar_terminos(contenido_limpio)
            # Formato Jerárquico en Markdown
            contenido_final = estructurar_jerarquia_markdown(contenido_unificado)

        nombre_md = f"{archivo.stem}.md"
        ruta_salida = destino / nombre_md

        # Frontmatter estándar en YAML
        yaml_frontmatter = f"""---
titulo: "{archivo.stem}"
extension_origen: "{ext}"
ruta_origen: "{archivo}"
fecha_procesamiento: "{datetime.now().strftime('%Y-%m-%d %H:%M:%S')}"
---

# {archivo.stem}

{contenido_final}
"""

        with open(ruta_salida, "w", encoding="utf-8") as f:
            f.write(yaml_frontmatter)

        procesados += 1
        print(
            f"[{datetime.now().strftime('%H:%M:%S')}] ✅ [{i}/{len(archivos)}] Procesado: {nombre_md}"
        )

        if i % 15 == 0:
            gc.collect()

    print(
        f"\n✔ ¡Proceso completado! Archivos Markdown generados en '{destino}'"
    )

# --- EJECUCIÓN (ruta de Google Drive) ---
ruta_drive = "/content/drive/MyDrive/0 Legislación SSO-20260724T184454Z-1-001/0 Legislación SSO/Resoluciones"
procesar_carpeta_sso(ruta_drive, "./salida_markdown_limpio")