# -*- coding: utf-8 -*-
"""procesamiento_documentos.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CwQ_xXD0wvjmYuC7xKEsWj4lgskBsK4r

## 1. Ი𐑼 Instalación de Dependencias
Instalación de paquetes externos requeridos para la manipulación de documentos en Python.
"""

!pip install pypdf python-docx openpyxl pandas -q

"""## 2. Ი𐑼 Importacion de modulos
Importación de librerías nativas y externas para la lógica del procesamiento.
"""

import os
import pandas as pd
import pypdf
import docx
import pprint
from docx import Document

"""## 3. Ი𐑼 Funciones de Extracción



*   leer_txt(): Extrae texto plano manejando codificación UTF-8.
*   leer_pdf(): Revisa y extrae el texto página por página usando pypdf.
*   leer_word(): Extrae párrafos de archivos .docx omitiendo líneas vacías.
*   leer_excel(): Recorre todas las pestañas de una hoja de cálculo y las convierte en texto estructurado.

*Ი𐑼 Lectura de archivos .txt*
"""

def leer_txt(ruta_archivo):
  """Abre y leer el contenido de un archivo de texto plano."""
  with open(ruta_archivo, 'r', encoding='utf-8', errors='ignore') as archivo:
    return archivo.read()

"""*Ი𐑼 Lectura de archivos .pdf*"""

def leer_pdf(ruta_archivo):
    """Extrae el texto de un archivo pdf"""
    lector = pypdf.PdfReader(ruta_archivo)
    texto = ""
    for pagina in lector.pages:
        contenido = pagina.extract_text()
        if contenido:
            texto += contenido + "\n"

    return texto

"""*Ი𐑼 Lectura de archivos .docx*"""

def leer_word(ruta_archivo):
  """Extrae los parrafos de un archivo word"""
  doc = Document(ruta_archivo)
  texto = [parrafo.text for parrafo in doc.paragraphs if parrafo.text.strip()]
  return "\n".join(texto)

"""*Ი𐑼 Lectura de archivos .xlsx*"""

def leer_excel(ruta_archivo):
    """Convierte las tablas en un formato de texto"""
    hojas = pd.read_excel(ruta_archivo, sheet_name=None)
    texto_total = []

    for nombre_hoja, df in hojas.items():
        texto_total.append(f"--- Hoja: {nombre_hoja} ---")
        texto_total.append(df.to_string(index=False))

    return "\n".join(texto_total)

"""## 4. Ი𐑼 (pipeline_procesar_documento)



1.   Valida la existencia del archivo en el sistema.
2.   Identifica la extensión del documento.
1.   Ejecuta la función de extracción correspondiente.
2.   Normaliza y limpia los espacios en blanco sobrantes.
1.   Retorna un diccionario estructurado con los metadatos y el contenido.

*Ი𐑼 Pipeline*
"""

def pipeline_procesar_documento(ruta_archivo):
    """Ingesta, extracción y procesamiento de documentos (Pdf, Word, Excel, Txt)"""
    if not os.path.exists(ruta_archivo):
        return f"Error: El archivo '{ruta_archivo}' no existe."

    # Extensión del archivo en minúscula
    ext = os.path.splitext(ruta_archivo)[1].lower()

    try:
        if ext == '.txt':
            texto_raw = leer_txt(ruta_archivo)
        elif ext == '.pdf':
            texto_raw = leer_pdf(ruta_archivo)
        elif ext in ['.docx', '.doc']:
            texto_raw = leer_word(ruta_archivo)
        elif ext in ['.xlsx', '.xls']:
            texto_raw = leer_excel(ruta_archivo)
        else:
            return f"Formato '{ext}' no soportado."

        # Remueve los espacios extras y saltos
        texto_limpio = " ".join(texto_raw.split())

        return {
            "nombre_archivo": os.path.basename(ruta_archivo),
            "contenido": texto_limpio,
            "tipo": ext,
            "longitud_caracteres": len(texto_limpio)
        }
    except Exception as e:
        return f"Error al procesar el archivo '{ruta_archivo}': {str(e)}"

"""## 5. Ი𐑼 Prueba"""

ruta_prueba = " " #Aquí va la ruta del archivo de prueba
resultado = pipeline_procesar_documento(ruta_prueba)
pprint.pprint(resultado)